### PR TITLE
only unlink if file exists

### PR DESCRIPTION
**Pull request by rohimma**
it was giving me an error that the file not exists on the second call

### CODE REVIEW

**Comment by leonjza** [comment]
Nice thanks for your contribution! 👍  

This is a totally legit case if the cache got cleared since the last read + expired check (even though that would have had to happen **super** fast), or maybe in the case of other filesystem problems.

Just want to check a few things quickly.

Are you manually calling the forget method on the FileCache here somehow where a condition would occur where the file no longer exists? If not, I worry that there might actually be a different bug (like how the filename is generated for the cache location or something like that). Unless I am being silly, I don't think there should be a case where the file does not exist as an expiration check [here](https://github.com/eveseat/eseye/blob/master/src/Cache/FileCache.php#L157) would be the reason the `forget()` method got called in the first place? Could you maybe dump the filenames [here](https://github.com/eveseat/eseye/blob/master/src/Cache/FileCache.php#L177) and [here](https://github.com/eveseat/eseye/blob/master/src/Cache/FileCache.php#L147) and check that they match, and maybe also inspect the filesystem to see if there are any discrepancies?

Secondly, I am wondering about how we should actually handle this case. Would it not be a tiny bit faster if we said `@unlink($cache_file_path)` instead of checking if the file exists first?

**Comment by rohimma** [comment]
it's a start xD 

not at home at the moment but i the code was something like this (using laravel on latest ubuntu):
```PHP
$user = Auth::guard('api')->user();
$authentication = new \Seat\Eseye\Containers\EsiAuthentication([
    'client_id' => env('EVEONLINE_KEY', ""),
    'secret' => env('EVEONLINE_SECRET', ""),
    'refresh_token' => $user->refreshToken,
]);

$esi = new \Seat\Eseye\Eseye($authentication);
$fleetData = $this->_esi->invoke('get', '/fleets/{fleet_id}/', [
    'fleet_id' => $request->fleet_id,
]);
```

as you can see i didn't set the cache, so it should use the default one.
but i couldn't find the correct cache path (on the virtual machine).

i will double check that later today.

**Comment by leonjza** [comment]
I see. In the case of Laravel, i'd configure the cache location to the `storage_path()`.

**Comment by rohimma** [comment]
this is the error: 
`unlink(/home/vagrant/website/storage/framework/cache/fleet/latest/fleets/xxxxxxxxxx//results.cache): No such file or directory`
&
`unlink(/home/vagrant/website/storage/framework/cache/fleet/latest/fleets/xxxxxxxxxx/members//results.cache): No such file or directory`

where "xxxxxxxxxx" is the fleet id
and and i did set the cache like this: storage_path('framework/cache')

here you can see the cache folder:
image

its missing the hash ?

**Comment by leonjza** [comment]
Yep looks like the hash is missing. Ill try and replicate this quickly and see what needs to be done to resolve that!

Can you update the pr to just add the `@` before the `unlink` in the meantime?

**Comment by leonjza** [comment]
Ok managed to replicate this locally. Working on a fix!

**Comment by leonjza** [comment]
Just released 0.0.5 with theses fixes in, as well as a minor improvement on cache usage.

**Pull request merged**
